package org.example.cs_antiques.service.impl;

import jakarta.annotation.PostConstruct;
import org.example.cs_antiques.dto.CartDTO;
import org.example.cs_antiques.dto.ProductDTO;
import org.example.cs_antiques.entity.Cart;
import org.example.cs_antiques.repo.AddToCartRepo;
import org.example.cs_antiques.service.AddToCartService;
import org.example.cs_antiques.util.VarList;
import org.modelmapper.ModelMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;

@Service
public class AddToCartServiceImpl implements AddToCartService {

    @Autowired
    private AddToCartRepo addToCartRepo;

    @Autowired
    private ModelMapper modelMapper;

    @Override
    public int addItemToCart(CartDTO cartDTO, String cusId) {
        cartDTO.setCusId(cusId);
        System.out.println("Cart DTO is : " + cartDTO);

        Cart cart = new Cart();
        cart.setCusId(cartDTO.getCusId());
        cart.setProductId(cartDTO.getProductId());
        cart.setImage(cartDTO.getImage());
        cart.setProductName(cartDTO.getProductName());
        cart.setCategory(cartDTO.getCategory());
        cart.setDescription(cartDTO.getDescription());
        cart.setPrice(cartDTO.getPrice());
        cart.setStock(cartDTO.getStock());
        cart.setQty(String.valueOf(cartDTO.getQty()));
        // cartId will be auto-generated by @PrePersist

        addToCartRepo.save(cart);
        return VarList.Created;
    }

    @Override
    public List<CartDTO> getAllProduct() {
        return addToCartRepo.findAll()
                .stream()
                .map(cart -> modelMapper.map(cart, CartDTO.class))
                .collect(Collectors.toList());
    }
}
